name: Deploy Blog app

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-app:latest

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/blog-app:latest &&
            docker stop blog-app || true &&
            docker rm blog-app || true &&
            docker run -d --restart unless-stopped -p 80:3000 --name blog-app ${{ secrets.DOCKER_USERNAME }}/blog-app:latest
          "
