name: Deploy Blog app

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-app:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy on VPS
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/blog-app:latest &&
            docker stop blog-app || true &&
            docker rm blog-app || true &&
            docker run -d --restart unless-stopped -p 80:3000 --name blog-app ${{ secrets.DOCKER_USERNAME }}/blog-app:latest
          "
